name: Deploy Artifacts

on:
  workflow_run:
    workflows: ["Build and Deploy"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout web-global-public
        uses: actions/checkout@v2

      - name: Download 54 TaskE artifact
        uses: actions/download-artifact@v2
        with:
          name: 54-TaskE-artifact
          path: ./54-TaskE-output

      - name: Download 54 TaskA artifact
        uses: actions/download-artifact@v2
        with:
          name: 54-TaskA-artifact
          path: ./54-TaskA-output

      - name: Move files to desired location
        run: |
          mkdir ./54
          mv ./54-TaskE-output/* ./54/TaskE
          mv ./54-TaskA-output/* ./54/TaskA